server:
  port: 8081
  mvc:
    view:
      prefix: /
      suffix: .html
  max-http-header-size: 1024000

spring:
  datasource:
    username: root
    password: Ikarosu1
    url: jdbc:mysql://www.Jian-Internet.com:3306/JianMask?useUnicode=true&characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true&autoReconnect=true&failOverReadOnly=false
    driver-class-name: com.mysql.jdbc.Driver
