server:
  port: 8081
  httpPort: 8082
  ssl:
      key-store: server.keystore
#         key-alias: jmask
      enabled: true
      key-store-password: Ikarosu
#         key-store-password: Ikarosu
      key-store-type: JKS
  mvc:
    view:
      prefix: /
      suffix: .html
  max-http-header-size: 1024000

spring:
  datasource:
    username: root
    password: Ikarosu1
    url: jdbc:mysql://www.Jian-Internet.com:3306/JianMask?useUnicode=true&characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true&autoReconnect=true&failOverReadOnly=false
    driver-class-name: com.mysql.cj.jdbc.Driver
